### ISSUE TITLE
Draw skybox in a single draw call

### ISSUE THREAD

**Issue by mrDIMAS** [rg3dengine/rg3d#114]
Currently, skybox is rendered as 6 separate planes with separate textures, but it could be drawn in a single draw call with cube map texture. Skybox is rendered in `renderer/deferred_light_renderer.rs`. To do this task, a set of sky box textures must be converted into a cube map (only on renderer side), and separate shader for rendering should be added. In the shader you could use position of vertex in world space to fetch cube map. As a mesh for skybox you could create cube geometry and flip it using -1 scale.

**Comment by vigdail** [comment]
Hello, I would like to work on this issue, but I have a few questions:
1. At what stage we need to convert separate faces into a cubemap? Should there be something like `SkyBoxBuilder` to which we provide faces and then it builds the actual `SkyBox` with only a cubemap? Or we need to build the cubemap on demand before rendering?
2. How to handle the situation when some faces have not been provided? Missing parts should be filled with zeroes in `bytes` parameter of `Texture::from_bytes` method, right?

**Comment by mrDIMAS** [comment]
Hi! The solution I've proposed is actually bad, it should be done as you wrote - make a SkyBoxBuilder which will construct a single cube map Texture. However there is one caveat - serialization. Currently, a texture for each side serialized separately, but when you'll convert a bunch of textures in a single one you'll lose connection with their respective source files. So to fix that, you should serialize textures for sides of skybox as usual (as it done in Visit trait implementation on SkyBox), but on load the cube map should be recreated. The point where cube map should be recreated is not so obvious - it can't be done directly in Visit trait implementation because in case of standalone scenes textures aren't pointing to actually loaded texture - they're just dummies with source file name inside - they'll be mapped to actual loaded resource on separate "resolving" stage. So the point to re-create cube map is `Scene::resolve` - what you need to do is just iterate over every camera and call your `SkyBox::update_cubemap` there. Also cube map should not be serialized, it will be "procedural" texture which is valid only for a single "session". At the renderer side you should use the cube map for rendering, instead of separate textures. Also there is already a mesh for the skybox so no need to create new one. As for missing textures - I think filling them with black (all zeros) is good.
