### ISSUE TITLE
API docs for 0.21.0 are broken (don't build)

### ISSUE THREAD

**Issue by saveriomiroddi** [rg3dengine/rg3d#150]
The API docs for v0.21.0 are broken - see https://docs.rs/crate/rg3d/0.21.0.

Build error [here](https://docs.rs/crate/rg3d/0.21.0/builds/410520), but I'm not familiar with the build. `cargo docs` builds fine one my (Linux) system.

By the way, there may be a typo in a doc attribute; see:

```
warning: unknown attribute `norun`. Did you mean `no_run`?
   --> rg3d-sound/src/context.rs:332:5
    |
332 | /     /// Returns internal state of the context.
333 | |     ///
334 | |     /// ## Deadlocks
335 | |     ///
...   |
347 | |     /// You'll get a deadlock, so general rule here is to not store result of this method
348 | |     /// anywhere.
    | |_________________^
    |
    = note: `#[warn(rustdoc::invalid_codeblock_attributes)]` on by default
    = help: the code block will either not be tested if not marked as a rust one or will be run (which you might not want)
```

**Comment by mrDIMAS** [comment]
Hi, I'm aware of this and unfortunately it can be fixed only by publishing a new version. I already fixed it in the repo and there is now a CI for docs to prevent such problems in the future. I'm planning to release 0.22 on this week.

**Comment by saveriomiroddi** [comment]
> Hi, I'm aware of this and unfortunately it can be fixed only by publishing a new version. I already fixed it in the repo and there is now a CI for docs to prevent such problems in the future. I'm planning to release 0.22 on this week.

Thanks for the reply. Keep up with the great work :)
