### ISSUE TITLE
Support custom backends/devices in rg3d-sound

### ISSUE THREAD

**Issue by OlegOAndreev** [rg3dengine/rg3d#152]
Currently the rg3d-sound library combines both sound processing and sound output. It would be nice to be able to use a different library for sound output (e.g. output to file, use SDL2 or CPAL, use dummy output for benchmarking etc.). Currently this is prevented by both mod device and context::State::render+SoundContext::SAMPLES_PER_CHANNEL being private.

The easiest way would probably be adding a couple of methods to SoundEngine:
```
pub fn render(buf: &mut [(f32, f32)])
pub fn required_buffer_len() -> u32
```

**Comment by mrDIMAS** [comment]
Yeah, rg3d-sound's backend set is kinda rigid now. However it is very easy to fix, but I don't know when I'll have time for this 🤔

**Comment by OlegOAndreev** [comment]
I am ready to prepare a PR if you are ok with the proposed API :)

**Comment by mrDIMAS** [comment]
If there won't be any threading issues, then I'm ok with the proposal. My main concern here is that SoundEngine instance is shared across main thread and mixer thread, and all processing is done in mixer thread. Main thread usually just adds/removes sources/effects/filter and modifies their state.

**Comment by OlegOAndreev** [comment]
I do not currently see any threading issues with the proposed API: the SoundEngine will still be shared between game threads and the audio thread and still must be locked when running render().

I've opened https://github.com/rg3dengine/rg3d/pull/154
