### ISSUE TITLE
building tutorial1-character-controller failed with 3 issues

### ISSUE THREAD

**Issue by cityKspicyChicken** [rg3dengine/rg3d#158]
I am new to use rust (also for rg3d)
I am using macOS Big Sur to build rg3d tutorial1-character-controller.

My building environment are:

rustc +nightly --version
rustc 1.56.0-nightly (d3e2578c3 2021-08-21)
with the latest rg3d 0.22.0

<img width="221" alt="Screen Shot 2021-08-22 at 9 15 18 PM" src="https://user-images.githubusercontent.com/36279386/130356649-0356f833-a85c-426a-a76a-9f376616ba04.png">

I build this tutorial with cargo build in the project root folder with the following errors, But  it seems context inconsistent, who can help me with it. 

<img width="891" alt="Screen Shot 2021-08-22 at 9 19 19 PM" src="https://user-images.githubusercontent.com/36279386/130356744-34d121b4-4871-413e-91b0-68aecc34c398.png">

**Comment by mrDIMAS** [comment]
Hmm, I forgot to update tutorials code to latest rg3d. I'll fix this asap.

**Comment by mrDIMAS** [comment]
I fixed this yesterday.
