### ISSUE TITLE
2d.rs in example folder is out of date

### ISSUE THREAD

**Issue by Dennis-Zhang-SH** [rg3dengine/rg3d#173]

**Comment by mrDIMAS** [comment]
What do you mean? It compiles without any issues.

**Comment by Dennis-Zhang-SH** [comment]
I got this error:

`error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> src\main.rs:48:48
    |
48  |                 .with_texture(resource_manager.request_texture("examples/data/starship.png", None))
    |                                                ^^^^^^^^^^^^^^^ ----------------------------  ---- supplied 2 arguments
    |                                                |
    |                                                expected 1 argument
    |
note: associated function defined here
   --> C:\Users\eayuhxz\.cargo\registry\src\github.com-1ecc6299db9ec823\rg3d-0.22.0\src\engine\resource_manager.rs:434:12
    |
434 |     pub fn request_texture<P: AsRef<Path>>(&self, path: P) -> Texture {
    |            ^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.`

and remove the none helps, but I don't know why ra keeps indicating me there still are errors.

**Comment by Dennis-Zhang-SH** [comment]
Okay, thanks for the explanation.
