### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by DuckEater54** [rg3dengine/rg3d#177]
I've noticed that certain lines have errors in them. For example the engine.render(TIMESTEP).unwrap(); part doesn't work. Render takes zero arguments so the timestep doesn't work.

**Comment by mrDIMAS** [comment]
Where did you find such piece of code 🤔 ? I've searched for it in both docs and the actual code and couldn't find it. Could you please post here actual outdated parts?

**Comment by DuckEater54** [comment]
nvm i did things wrong which led to argument errors
