### ISSUE TITLE
`Inspect` proc macro should also generate constants with field names

### ISSUE THREAD

**Issue by mrDIMAS** [rg3dengine/rg3d#193]
When using `Inspector` you forced to use string literals to distinguish `PropertyChanged` messages, using raw string literals is very bug prone and this could be improved by using generated string literals which then could be used as `TypeName::FIELD_NAME`- this will result in compiler error if a property name has changed. I propose to generate property names as constants in `impl TypeName`. An example for structures is quite simple:

```rust
#[Inspect]
struct Foo {
  bar: u32
}

// This should be generated
impl Foo {
  pub const BAR: &'static str = "bar";
}
```

Enums are more complex, it should also add variant name prefix to the constant name:

```rust
#[Inspect]
enum Baz {
  Struct { named_field: f32 },
  Tuple(u32, f32),
  Unit,
}

// This should be generated

impl Baz {
  pub const STRUCT_NAMED_FIELD: &'static str = "named_field";
  pub const TUPLE_0: &'static str = "0";
  pub const TUPLE_1: &'static str = "1";
  // Baz::Unit is ignored because it has no fields.
}
```

**Comment by toyboot4e** [comment]
Let me try :)
