### ISSUE TITLE
Questions regarding this game engine.

### ISSUE THREAD

**Issue by Joe23232** [rg3dengine/rg3d#196]
Hi, I have some questions regarding this game engine:
1. How does it differ to the [`Bevy`](https://bevyengine.org/) game engine, especially in regards to its ease of use in comparison to `bevy`?
2. Does it integrate its own ECS?
3. If I used the game editor, does it do a lot of the heavy lifting for me, for example if I position a cube at a certain point, I don't have to manually code this?
4. Am I using Rust to code my game if using the game editor?
5. If `4` is applicable, then does (I am not sure if I am explaining this correctly) does the code get compiled to machine code, not something like where [`godot`](https://godotengine.org/) has some sort of linker for [`gdnative-rust`](https://github.com/godot-rust/godot-rust) which has some performance drawbacks or something, its all pure machine code without any costs to performance, am I correct?
6. Is there a lot more coding compared to something like Unity if I wanted to move a simple object?
7. If exporting my objects from Blender, what format does it support?

**Comment by mrDIMAS** [comment]
1. Hard to tell, I never used it. But I think rg3d has more advanced 3D and in general is ready for production.
2. No.
3. rusty-editor is not a **game** editor, it is a **scene** editor - this means that it allows you building your own scenes to use them later in your game. Currently it is not possible to add/remove/edit **game** entities using the editor. You may think of it as a Blender or 3Ds max.
4. Yes
5. Your game just loads a scene made in the editor, so your game is in native code with no performance drawbacks.
6. No, for example, to move an object you should do something like `scene.graph[node_handle].local_transform_mut().set_local_position(Vector3::new(1.0, 2.0, 3.0))`
7. FBX

**Comment by Joe23232** [comment]
@mrDIMAS  @Voodlaz Thanks guys for your comments.

Isn't FBX proprietary? I heard that Godot couldn't use FBX due to license issue or something? How did you guys manage to use FBX, cause I thought this is something that Autodesk owns?

**Comment by mrDIMAS** [comment]
Nothing stops you from writing your own loader of FBX (which I did), I think Godot can't use FBX SDK due to its license.

**Comment by Joe23232** [comment]
> Nothing stops you from writing your own loader of FBX (which I did),

Ah I see mate.

> I think Godot can't use FBX SDK due to its license.

Yeah they could have written their own loader though.

**Comment by MiniaczQ** [comment]
For people who came here to know how it's different from Bevy, here's my take:
- RG3D doesn't have ECS, Bevy does,
- RG3D will start you closer to something good looking, but probably at less/more difficult control over detail.
- RG3D has a built in rapier physics engine, but Bevy can also use it with very few extra steps,
- RG3D seems to have more UI widgets than Bevy,
- RG3D has a scene editor, but you should be better off using Blender (my guess is that it's gonna shine after more features are added),
It seems that RG3D tries to show off some of they stuff that it doesn't really add, but just include (like serde), don't wanna offend anyone, just seems a bit obnoxious. I can see how this may help people who are just getting into Rust.
I'm not sure how good this engine is with plugins, which is a big positive for Bevy, where you can get most of RG3D features by adding plugins.
Personally I'd prefer Bevy for my current project, but I'm looking forward to how this can develop.

**Comment by Joe23232** [comment]
@MiniaczQ 

Interesting mate.

So wait I can use Blender over `rusty_editor` for my game scene? How would that be possible mate?

**Comment by mrDIMAS** [comment]
@MiniaczQ
 
>     * RG3D has a scene editor, but you should be better off using Blender (my guess is that it's gonna shine after more features are added),

Why? Could you please elaborate on that?

>     * It seems that RG3D tries to show off some of they stuff that it doesn't really add, but just include

Am I missing something, but I think added a lot of its own stuff. I want to know more :)

**Comment by Joe23232** [comment]
> Why? Could you please elaborate on that?

Maybe its easier to use Blender to navigate over the rust_editor but even then I wouldn't understand how you can make an entire game in Blender?

**Comment by mrDIMAS** [comment]
Closing this due to large period of inactivity.

**Comment by CoreyCole** [comment]
I'm wondering how bevy and fyrox can work together? Can I use bevy to keep track of positions/velocities/collision with bevy-rapier inside a fyrox game world?

**Comment by mrDIMAS** [comment]
Fyrox has its own wrapper for Rapier physics. All you need to do is to create appropriate physics nodes and it will work - see https://fyrox-book.github.io/fyrox/physics/physics.html and following chapters.
