### ISSUE TITLE
Can't seem to re-use same material for different meshes

### ISSUE THREAD

**Issue by w-flo** [rg3dengine/rg3d#197]
Hi!

I've been toying around with rg3d a bit and so far, I really like it! Thank your very much for sharing it. I don't have a lot of experience with graphics programming or Rust, so please let me know if I'm getting anything wrong.

I'm trying to render different meshes using the same texture (e.g. a street texture that is used for various streets). So I create one `Arc<Mutex<Material>>` for each texture and pass a `.clone()` of the material `Arc` I want for each Mesh into the SurfaceBuilder. I hope that's the way I'm supposed to be sharing that Material!

However, it turned out that rg3d would always re-render the geometry of the first object every time I wanted another object using the same texture to be drawn. It does respect the transform for each mesh node though. So instead of getting many streets that are shaped differently, I get copies of the same street in different places.

I looked at the rg3d batching code and it seems like the SurfaceData of any mesh node is simply getting discarded if it turns out that the surface uses a material for which a batch already exists in the batch storage. I feel like this is a bug and it should add the new surface data to the batch somehow, unless the same mesh is to be rendered (using the same material) at another position already, in which case it could use instanced draw calls instead. Or maybe I'm using rg3d wrong?

To reproduce, I extended the example "simple", trying to add a pillar next to the animated monster model and the floor. After adding the pillar, which shares a material with the floor, the floor is no longer rendered. Instead, there are two pillars.
```diff --git a/examples/simple.rs b/examples/simple.rs
index 2059d47..ad6cb7d 100644
--- a/examples/simple.rs
+++ b/examples/simple.rs
@@ -127,6 +127,23 @@ impl GameSceneLoader {
             )
             .unwrap();
 
+        let material_mutex = Arc::new(Mutex::new(material));
+
+        // Add pillar.
+        MeshBuilder::new(
+            BaseBuilder::new().with_local_transform(
+                TransformBuilder::new()
+                    .with_local_position(Vector3::new(-10.0, 0.0, 0.0))
+                    .build(),
+            ),
+        )
+        .with_surfaces(vec![SurfaceBuilder::new(Arc::new(RwLock::new(
+            SurfaceData::make_cylinder(20, 0.5, 25.0, true, &Matrix4::identity()),
+        )))
+        .with_material(material_mutex.clone())
+        .build()])
+        .build(&mut scene.graph);
+
         // Add floor.
         MeshBuilder::new(
             BaseBuilder::new().with_local_transform(
@@ -140,7 +157,7 @@ impl GameSceneLoader {
                 25.0, 0.25, 25.0,
             ))),
         )))
-        .with_material(Arc::new(Mutex::new(material)))
+        .with_material(material_mutex.clone())
         .build()])
         .build(&mut scene.graph);
 
```

**Comment by mrDIMAS** [comment]
Yep, that is a bug, I think batch id computed incorrectly. It does not take the surface data into account - https://github.com/rg3dengine/rg3d/blob/master/src/scene/mesh/surface.rs#L959 , it should also merge this id with address of surface data. So it should be something like this. 

```rust
    pub fn batch_id(&self) -> u64 {
        (&*self.material as *const _ as u64) ^ (&**self.data.as_ref() as *const _ as u64)
    }
```

Probably it is better to use Hasher to combine ids, instead of XOR op.

**Comment by w-flo** [comment]
This line seems to work (unwrap added, possibly a bad idea?) and produces correct rendering results (as far as I can tell – I guess the remaining rendering issues are not in rg3d but my own code):
```rust
        (&*self.material as *const _ as u64) ^ (&**self.data.as_ref().unwrap() as *const _ as u64)
```
Thank you! :-)
