### ISSUE TITLE
Regardless if I use the gui game editor or not, can materials still be rendered into the game scene?

### ISSUE THREAD

**Issue by Joe23232** [rg3dengine/rg3d#203]
I understand that `rusty-editor` currently only supports textures, however, I was wondering if the core of the game engine supports materials as well or is this something that is being worked on?

If it is something that is being worked on, is there an issue tracker or something where I can track the progress?

**Comment by Joe23232** [comment]
@mrDIMAS 

> currently rg3d's FBX importer is not able to fully map FBX material to engine's material.

I believe the support for materials is currently being worked on, is there some issue I can track or something?

**Comment by mrDIMAS** [comment]
FBX importer now supports diffuse color (fixed in #164), so I think this issues can be closed too.

**Comment by Joe23232** [comment]
@mrDIMAS That is awesome mate =D

**Comment by Joe23232** [comment]
@mrDIMAS Can it support `emissions` and `glossy` properties or is it being worked on?
