### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by DuckEater54** [rg3dengine/rg3d#218]
Following the examples files, I am testing each file with the following directory. I will update this with each test I do.
```
Root
|----src
|     |----shared
|     |      |----mod.rs
|     |----main.rs
|----Cargo.toml
```

I have tested this without changing anything in the files and directly copying them.
The error log for UI is [here](https://pastebin.com/W1c2iXJi)

**Comment by mrDIMAS** [comment]
I'm pretty sure that you have outdated local copies of examples, engine's examples are fine.

**Comment by w-flo** [comment]
I guess it's the other way round, you're using example files from current git, but older rg3d v0.23.1 from crates.io? You need the current git rg3d if you're using the current git examples because there are regular breaking changes to the API at this stage.

**Comment by DuckEater54** [comment]
That is probably correct, I don't have access to my computer right now so I can't check

**Comment by mrDIMAS** [comment]
Closing this because examples are fine, CI also proves that.
