### ISSUE TITLE
Reexports and docs

### ISSUE THREAD

**Issue by martin-t** [rg3dengine/rg3d#231]
After #230 was merged, i realized there's probably a better solution - `#[doc(inline)]` - e.g.:
```rust
#[doc(inline)]
pub use rg3d_sound as sound;
```

This preserves the docs from the original crate (although it doesn't mention anywhere that it's a reexport but that's just a tiny downside).

Should i make a PR to use `#[doc(inline)]` instead?

This made me wonder though - should the other crates reexport subcrates such as `core` publicly? When searching, it results in for example `Pool` being found 4 times. Some items like `Vector` are even worse. I think using the main rg3d crate as a full game engine is the primary usecase. If people wanna use the other crates separately, they should be able to put for example `nalgebra` and `rg3d-ui` in their Cargo.toml and be able to use both together without having to go through `rg3d_ui::core::algebra`.

There's a middle ground - use a (default) feature to reexport core, nalgebra and others when subcrates are used standalone but don't reexport when used from the rg3d crate.

**Comment by mrDIMAS** [comment]
I think `#[doc(inline)]` is better then.  Re-export is fine, I don't think it is a big issue.

**Comment by mrDIMAS** [comment]
I'm closing this, since PR was merged.
