### ISSUE TITLE
Idea: Shaders

### ISSUE THREAD

**Issue by Eragonfr** [rg3dengine/rg3d#69]
I've seen some interesting usages of shaders in many games. And I think that having a shaders support inside the game engine itself is good.

In my head shaders can be used in many ways to improve the game graphics.
They should be optional, so the game can run without any shader, it's better for my toaster computer

**Comment by mrDIMAS** [comment]
Custom shaders are good indeed, but this will require to refactor the renderer. Not sure when I'll have time for this.

**Comment by pgm-rs** [comment]
Yes, I thought of it. I also thought about the idea of switching OpenGL to Vulkan.
I wanted to make a game engine using the knowledge of other game engine by view their source code. Like Godot and this. This is the link to my post 
[https://www.reddit.com/r/rust_gamedev/comments/nbaqqp/a_game_engine/?utm_source=share&utm_medium=web2x&context=3](url)

**Comment by mrDIMAS** [comment]
Closing this in favor of #134 since it adds more wide support for custom rendering.
