### ISSUE TITLE
Replace custom WAV loader with existing crates

### ISSUE THREAD

**Issue by mrDIMAS** [rg3dengine/rg3d#86]
rg3d-sound has custom loader for WAV format which handles simplest case where samples are not compressed and in some cases custom loader behaves weirdly. It should be replaced with one of existing solutions (maybe [hound](https://crates.io/crates/hound))

**Comment by samuel-weinstein-cs** [comment]
i am working on integrating hound

**Comment by mrDIMAS** [comment]
Awesome, thank you!

**Comment by samuel-weinstein-cs** [comment]
@mrDIMAS I am thinking about re-factoring the enum Decoder into a trait, it would make adding more audio formats in the future easier

**Comment by mrDIMAS** [comment]
Sounds like a great idea!
